### ISSUE TITLE
Invalid private key on init

### ISSUE THREAD

**Issue by sooheon** [robert-stuttaford/bridge#2]
`make compile serve` throws an error about datomic. Apparently it's failing to provide an in-mem db by default? Haven't tried running a transactor yet.

```
source bridge.env && clojure -m bridge.service
Starting on port  8080
Exception in thread "main" clojure.lang.ExceptionInfo: Error on key :datomic/dev-data when building system {:reason :integrant.core/build-threw-exception, :system {:datomic/connection {:datomic/mode :peer, :datomic/conn #object[datomic.peer.LocalConnection 0x7aba206b "datomic.peer.LocalConnection@7aba206b"]}}, :function #object[clojure.lang.MultiFn 0x1980962c "clojure.lang.MultiFn@1980962c"], :key :datomic/dev-data, :value {:datomic {:datomic/mode :peer, :datomic/conn #object[datomic.peer.LocalConnection 0x7aba206b "datomic.peer.LocalConnection@7aba206b"]}}}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at integrant.core$build_exception.invokeStatic(core.cljc:208)
	at integrant.core$build_exception.invoke(core.cljc:207)
	at integrant.core$try_build_action.invokeStatic(core.cljc:219)
	at integrant.core$try_build_action.invoke(core.cljc:216)
	at integrant.core$build_key.invokeStatic(core.cljc:225)
	at integrant.core$build_key.invoke(core.cljc:221)
	at clojure.core$partial$fn__5563.invoke(core.clj:2624)
	at clojure.core.protocols$fn__7852.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__7852.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__7807$G__7802__7816.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__7835.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7835.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$reduce.invoke(core.clj:6730)
	at integrant.core$build.invokeStatic(core.cljc:244)
	at integrant.core$build.invoke(core.cljc:228)
	at integrant.core$init.invokeStatic(core.cljc:321)
	at integrant.core$init.invoke(core.cljc:313)
	at integrant.core$init.invokeStatic(core.cljc:318)
	at integrant.core$init.invoke(core.cljc:313)
	at bridge.service$_main.invokeStatic(service.clj:47)
	at bridge.service$_main.doInvoke(service.clj:45)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'init-key' for dispatch value: :datomic/dev-data
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at integrant.core$try_build_action.invokeStatic(core.cljc:217)
	... 33 more
make: *** [serve] Error 1
```

**Comment by sooheon** [comment]
Same issue with datomic starter transactor and `export`ing the relevant variable.

**Comment by sooheon** [comment]
Make figwheel works.

**Comment by robert-stuttaford** [comment]
Somehow I missed seeing this until now. Thanks for the feedback, I'll make sure it's all working correctly soon.

**Comment by robert-stuttaford** [comment]
Fixed, thanks @sooheon https://github.com/robert-stuttaford/bridge/commit/7c4e0f18b1c64d93f2f56145b8ec16e11295cb71#diff-93447574dc1433d263956008ee206cea

**Comment by sooheon** [comment]
Thanks for the invaluable learning resource!
